apiVersion: apps/v1

kind: Deployment

metadata:
  name: ann-mnist-api
  namespace: ann-mnist

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: ann-mnist-api

  template:
    metadata:
      labels:
        app: ann-mnist-api

    spec:
      containers:
        - name: ann-mnist-api

          image: ghcr.io/pkai21/ann-mnist-dev:sha-1b9b847f9e5e304fa09ce454d30fd4fcb0d5e7bb

          imagePullPolicy: IfNotPresent

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1Gi

          ports:
            - containerPort: 8000

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10