apiVersion: v1

kind: Service

metadata:
  name: ann-mnist-api
  namespace: ann-mnist

spec:
  type: NodePort

  selector:
    app: ann-mnist-api

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30081